### ISSUE TITLE
Could not find a declaration file for module 'react-native-vector-image'

### ISSUE THREAD

**Issue by DEVfancybear** [oblador/react-native-vector-image#1]
I got an error when installing lib with the `react native typescript` template

**Comment by DEVfancybear** [comment]
![Screen Shot 2021-04-23 at 10 14 19 PM](https://user-images.githubusercontent.com/47390684/115892343-43ca4d00-a481-11eb-85f6-db512beaac2a.png)

**Comment by oblador** [comment]
Hi! Typescript definitions added in [0.2.0](https://github.com/oblador/react-native-vector-image/releases/tag/v0.2.0)
