### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by jagadishg** [oblador/react-native-vector-image#13]
I'm planning to use this library on my project. I noticed that its relatively new project and doesn't really have huge downloads. I also see that currently you are the only contributor. So I just wanted to know if this project is active or not.

**Comment by oblador** [comment]
It's because it is a very new project. It is active, let me know if you have any issues.

**Comment by jagadishg** [comment]
Thats awesome!
I'm facing an issue while generating native assets. I will close this issue and open a new one with proper title.
