### ISSUE TITLE
Invalid --ios-output argument, folder doesn't exist

### ISSUE THREAD

**Issue by sasilta** [oblador/react-native-vector-image#16]
While trying to generate the vector assets in ios using the command ''yarn react-native-vector-image generate', I am getting the 'Invalid --ios-output argument, folder doesn't exist'. In android everything seems to be working fine. Am i missing any configurations? 

I also tried with giving folder path through the command 'yarn react-native-vector-image generate --ios-output ios/Appname/Image.xcassets'. The command runs successfully but I do not see any assets generated to be recognized by ios app.

I have following environment:
"react-native": "0.64.2",
"@klarna/react-native-vector-drawable": "^0.3.0",
"react-native-vector-image": "^0.3.2",

yarn 1.22.10
I am also using react native boiler plate 'ignite'

**Comment by oblador** [comment]
Does the folder `ios/Appname/Images.xcassets` exist? What if you pass the absolute path to it?

**Comment by sasilta** [comment]
The folder exists in the project. But it worked now after giving the absolute path.

Thank you

**Comment by ShingLi** [comment]
I also encountered this issue. After printing options.iosOutput, I found that it was caused by my modification to the app.json. So, can we optimize the error message?
