### ISSUE TITLE
[Q] is there any benchmarking done on size and perfomance 

### ISSUE THREAD

**Issue by hasn-ab** [oblador/react-native-vector-image#37]
Hi, this looks really promising. I just wanted to know if there is any benchmarking done when compared to react-native-svg?

I tried using react-native-svg in one of our projects, and it increased the bundle size. 

Since this library uses native assets, is it safe to assume it would have zero impact on bundle size?

**Comment by oblador** [comment]
Yes exactly, this is more or less equivalent to using a bitmap image in that regard.
