### ISSUE TITLE
Cannot find module 'metro/src/Server'

### ISSUE THREAD

**Issue by nick-burczyk-cs** [oblador/react-native-vector-image#39]
When trying to run `react-native-vector-image generate`, we are no longer able to generate and receive the message below. Relevant packages being used:

- react-native: 0.64.2
- react-native-vector-image: ^0.3.3
- @klarna/react-native-vector-drawable: 0.1.2,

```
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'metro/src/Server'
Require stack:
- /path/to/node_modules/react-native-vector-image/src/cli/getAssets.js
- /path/to/node_modules/react-native-vector-image/src/cli/generateAssets.js
- /path/to/node_modules/react-native-vector-image/src/cli/index.js
- /path/to/node_modules/react-native-vector-image/bin/react-native-vector-image.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/path/to/node_modules/react-native-vector-image/src/cli/getAssets.js:1:16)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/path/to/node_modules/react-native-vector-image/src/cli/getAssets.js',
    '/path/to/node_modules/react-native-vector-image/src/cli/generateAssets.js',
    '/path/to/node_modules/react-native-vector-image/src/cli/index.js',
    '/path/to/node_modules/react-native-vector-image/bin/react-native-vector-image.js'
  ]
}
```
I have tried reverting to version 0.3.2 and still get the same error. Is my current version (0.3.3) compatible with RN 64.2? Or is the version not the issue?

**Comment by oblador** [comment]
Yep, you need to use a more recent version of react native/metro. You should have gotten peer dependency warnings about it (yes i know those warnings are broken/numerous).

**Comment by nick-burczyk-cs** [comment]
So I need to upgrade React Native itself? What version is the minimum supported?

**Comment by oblador** [comment]
I'm a bit unsure of how the metro version maps to react native. Maybe you can start with telling me what version you have and if maybe you have multiple? Are you using yarn? If so, what does `yarn why metro` yield?

**Comment by nick-burczyk-cs** [comment]
Looks like we are running metro 0.76.5. We don't have yarn configured, so I couldn't run `yarn why`

**Comment by nick-burczyk-cs** [comment]
But it looks like from the assets in your release of 0.3.2 that the project just expects metro >=0.58.0

**Comment by oblador** [comment]
Ok, that's a pretty recent version which afaik should be supported. Are you using plain old npm?

**Comment by nick-burczyk-cs** [comment]
we are

**Comment by oblador** [comment]
I'm a bit surprised of your metro version being so recent with your react native version being so old. Do you have multiple versions of metro installed by any chance? Maybe this tool can help you https://www.npmjs.com/package/find-duplicate-dependencies

**Comment by nick-burczyk-cs** [comment]
Sorry, we don't have metro listed explicitly, so npx was just getting the latest version. In node_modules/react-native/node_modules/metro/package.json, it looks like metro is 0.64.0

**Comment by oblador** [comment]
Aha, that seems to be the problem then. You could solve it by adding metro as a dependency to your project, just use the same version as RN uses.

**Comment by nick-burczyk-cs** [comment]
OK. That seems to have fixed the issue with our generate script! But now I am back at where I started. The script succeeds (I think) but with a single error file, 
```
Failed to generate vector assets
src/assets/images/svg/brands/hopper.svg: line 4: Semitransparent mask cannot be represented by a vector drawable
```
despite the error I now have ~60 new json, xml and pdf files. So it seems to be working except on that one file. 

But when I try to use certain icons, I still get an error on the device that says

```
Error while updating property 'resourceName' of a view managed by RNVectorDetails

null

Unable to find resource location_start_svg_HASH in <namespace>
```
this was the original error that I got. I assumed I needed to generate for newer icons to be included. Now that generation seems to be working, I still can't use newly-added icons.

**Comment by nick-burczyk-cs** [comment]
I tried rebuilding the app with `npx react-native run-android` but I didn't clear any cache or anything between generating and running it again. Do you have a suggestion there?

**Comment by nick-burczyk-cs** [comment]
iOS does work actually. It is just an android issue now. I did see the note in the Readme that the files need to be imported somewhere in the project in order to be generated. That also seems to be the case (only imported ones are being generated). 

But now the error does seem to be with android specifically

**Comment by nick-burczyk-cs** [comment]
@oblador Thank you so much for your help. I started a new branch and followed this discussion again and it worked the second time around. 

I very much appreciate all your responsiveness and support!
