### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by mizinin** [oblador/react-native-vector-image#40]
Can't install react-native-vector-image with npm 8.x due to error:

`Invalid tag name "=>0.4.0" of package "@klarna/react-native-vector-drawable@=>0.4.0": Tags may not have any characters that encodeURIComponent encodes.`

**Comment by mizinin** [comment]
I think there is must be `>=0.4.0` version, not `=>0.4.0`

**Comment by oblador** [comment]
Fixed in [0.4.3](https://github.com/oblador/react-native-vector-image/releases/tag/v0.4.3)
