### ISSUE TITLE
Not install @klarna/react-native-drawable-android

### ISSUE THREAD

**Issue by DEVfancybear** [oblador/react-native-vector-image#7]
I couldn't install this lib on [npm](https://www.npmjs.com/package/@klarna/react-native-vector-drawable) nor `yarn`, and the `repo` lib won't be available anymore

**Comment by oblador** [comment]
Sorry docs are wrong, it should be @klarna/react-native-vector-drawable

**Comment by DEVfancybear** [comment]
Hmm, seems still incorrect, the repo is inaccessible

![Screen Shot 2021-04-27 at 5 28 50 PM](https://user-images.githubusercontent.com/47390684/116227239-1f6eb900-a77e-11eb-99f0-d29695158ae7.png)

**Comment by oblador** [comment]
Repo is not live on github yet, it needs some work, but i'll get on that soon enough.
